apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: test-idp
spec:
  connection:
    postgres:
      host:
        value: test-idp-postgresql
      password: 
        valueFrom:
          secretKeyRef:
            name: test-idp-postgresql
